### ISSUE TITLE
Improved iOS Xcode install/configuration instructions

### ISSUE THREAD

**Issue by kristianmandrup** [xinthink/react-native-material-kit#120]
For ppl struggling with XCode

"Add node_modules/react-native-material-kit/iOS/RCTMaterialKit.xcodeproj to your xcode project, usually under the Libraries group"

See the yellow folders in your project view to the top left. Find `Libraries` folder. Drag the mentioned `.xcodeproj` file there.

"Add libRCTMaterialKit.a (from Products under RCTMaterialKit.xcodeproj) to build target's Linked Frameworks and Libraries list"

Click your project (top left), then select `general` tab and find section `Linked Frameworks and Libraries list` at the bottom. Now find the `RCTMaterialKit.xcodeproj` you added and open it in the project view, then expand `Products` folder and find the file mentioned. Now drag it over into the list of linked libraries.

For me the file `libRCTMaterialKit.a` was red before I dragged it over and still red after. 
Hope it still works!

**Comment by cablegunmaster** [comment]
As a developer coming from the android environment its still a bit unclear how to proceed.

1. install with NPM done.
2. install on the android app done.
3. install on IOS... its a bit unclear what you refer as the `Library.` folder. 
Can there be a generic I am a idiot instructions, for I have no idea how to implement it on IOS.

The android instructions itself, I find are very clear to follow. 

Please help me, by saying add this to this file and that to that file underneath this option.

**Comment by xinthink** [comment]
Xcode is a bit different to Android Studio or Eclipse. 
`Libraries` is something called 'Group' (kind of virtual folders), people usually manipulate them by drag & drop (instead of by editing the .xcodeproj file), if your project is created by `react-native init`, it should already be there:
![_2016-04-12_ 1_14_35](https://cloud.githubusercontent.com/assets/390805/14450410/ae39203c-00b0-11e6-9c89-1e2f15f386f0.jpg)

you can add files or projects to the group by drag & drop or context menu, and then follow the awesome instructions above written by @kristianmandrup :beer:
Good luck!

**Comment by cablegunmaster** [comment]
Ah thanks, I started it with the android approach. That is why my experience with ios is minor. Gonna look up how to init correctly :).

**Comment by alexprice91** [comment]
Closing this for now. Would welcome `PR` for README
