### ISSUE TITLE
Switch component shows an error, with RN 0.22

### ISSUE THREAD

**Issue by andramarin** [xinthink/react-native-material-kit#134]
Here is the error: 
" undefined is not an object (evaluating Thumb.defaultProps.style) "

I followed the error in switch.js  lib/mdl, and here is the problem, line 130: Thumb.defaultProps.style,

For now I solve the error by removing this line of code, though I am not sure of your intentions there, what did you want to achieve? 

Thanks, 
Andra

**Comment by mmazzarolo** [comment]
Same issue on React-Native 0.22 on every component referencing the `defaultProps` (i.e. Switch and Checkbox).
It seems it can be fixed with the following steps:
1. Set `defaultProps` and `propTypes` as static objects on the component
2. Don't reference `defaultProps` directly anymore: `this.props.propName` has already the value set in `defaultProps`.

This fixed the issues for me, let me know if it works for you too (if needed I can send a pull request with this fix).

You can see an example [here, check the static objects and the line 181](https://gist.github.com/mmazzarolo/9c0759d4b9e713a3ae710a3517434316).

P.S.: I don't use builders... hope this doesn't break them.

**Comment by trabianmatt** [comment]
I believe this was fixed via 116760340ca7d734a9768c6d1d464cdddf9e2221.

**Comment by Crash--** [comment]
I close this issue since it's a problem with RN 0.22. If you still have it with latest version, please feel free to reopen.
