### ISSUE TITLE
MKTextField does not change width upon orientation change

### ISSUE THREAD

**Issue by vonovak** [xinthink/react-native-material-kit#174]
hello! thanks for this awesome lib.
I noticed that when changing screen orientation, the width of MKTextField stays the same.

How to reproduce:
1create MKTextField
2 run app in portrait mode
3 switch to landscape - MKTextField will keep its width

**Comment by kencana-voilaah** [comment]
humm, I am not sure if i am doing the right thing, but to make it work, I added a couple of thing in Textfield.js

1. in TextField component
- I added in onLayout event listener, to grab the latest width value
- added in 3 state value: width, height, focus
- in onLayout method, I will set the latest width and height, and check if the focus state is true, if it is, i will call `this._aniStartHighlight(true);`, so that the highlighted line adjusted accordingly
- I will then pass a width styling into TextInput
- I will also pass lineLength prop to the Underline

2. in Underline component
- added in some expression to grab the lineLength prop as the width or just use the state lineLength


seems like a dirty hack, but that's how i handle it at the moment. let me know if there is any better implementation for this :)

**Comment by jurassix** [comment]
@xinthink are you open to a PR to fix this issue? I'm about to fork and fix this for my needs, would be happy to contribute back via PR if this this something you will accept. Not supporting orientation changes is a critical enhancement for my needs.

**Comment by jurassix** [comment]
@kencana-voilaah 

The best solution I've found is to have <TextField /> call the internal `_doMeasurement` on any layout change.

Submitting PR now.

code sample:
```
<View style={this.props.style} onLayout={this._doMeasurement.bind(this)}>
```
