### ISSUE TITLE
React Native 0.36 support

### ISSUE THREAD

**Issue by mschipperheyn** [xinthink/react-native-material-kit#261]
RN 0.36 has some breaking changes to the way flex box is processed https://github.com/facebook/react-native/releases/tag/v0.36.0

On my application it breaks the floating label textinput.

**Comment by yustnip** [comment]
Can inform that Slider is broken. A thumb position isn't updated but at the same time a value is changed.

**Comment by mschipperheyn** [comment]
I'm concerned about the lack of follow up to these blocking breaks on this library

**Comment by andrewnoh** [comment]
My sliders appear to work on 0.36 and 0.37.

**Comment by rseemann** [comment]
any workaround for broken inputs?

**Comment by rseemann** [comment]
There seems to be a problem at this styling here: https://github.com/xinthink/react-native-material-kit/blob/master/lib/mdl/Textfield.js#L539

**Comment by dgdavid** [comment]
Also [`cardStyle`](https://github.com/xinthink/react-native-material-kit/blob/1db0f44199a7e7f57bd878060678090eb0511865/lib/theme.js#L99) and [`cardImageStyle`](https://github.com/xinthink/react-native-material-kit/blob/1db0f44199a7e7f57bd878060678090eb0511865/lib/theme.js#L113) have yet the `flex: 1` property, which should be removed.

Just for the records, I'm getting the `View was rendered with explicitly set width/height but with a 0 flexBassis` error because of this.
