### ISSUE TITLE
Checkbox render issue (IOS)

### ISSUE THREAD

**Issue by jitenderchand1** [xinthink/react-native-material-kit#284]
Checkbox did not render correctly. But the other thing are link radiobutton and slider are working perfectly.

Version detail

`"react-native-material-kit": "^0.3.4",`
`react-native:0.39.2`

![screen shot 2017-01-05 at 10 29 25 pm](https://cloud.githubusercontent.com/assets/19687185/21689475/70d72e64-d396-11e6-9415-2fffdcfe1414.png)

**Comment by Crash--** [comment]
Generally when you see a red box it's because RNMK is not well linked. By that I mean the native code is not linked correctly. Check if `react-native link` has done its own work (check the manually section here https://github.com/xinthink/react-native-material-kit#android) 

If others components are working it's mainly because they don't need native code.

**Comment by jitenderchand1** [comment]
Thanks for quick response. I am looking into it now

**Comment by jitenderchand1** [comment]
It is working fine after linking. Thanks!
