### ISSUE TITLE
Native component does not exist in CRNA app

### ISSUE THREAD

**Issue by mannyhenri** [xinthink/react-native-material-kit#307]
I tried using react-native-material-kit with the new create-react-native-app and some of it works but the app screams about MKTouchable & TickView when using...

`import { MKTextField, MKColor, MKButton } from 'react-native-material-kit';`

And it gives me this error....

`Warning: Native component for "MKTouchable" does not exist`

for both of the above mentioned.

**Comment by Crash--** [comment]
We've some native code in order to bring performance & UX to our end-user. We can't replace it at the moment. If someone wants to port the native parts to JS only, feel free to add this as an option ;)

**Comment by chenop** [comment]
Thanks @Crash-- but can you please elaborate?
The whole purpose in RN is to use JS to create native android & IOS apps - what do you mean that you need to port native parts to JS?

Or maybe the problem is with apps created with create-react-native-app?

Sorry I'm a newbie and I'll be happy to use this libray.

**Comment by Crash--** [comment]
React Native lets use write app with JavaScript but also in native code (Obj-C / Swift & Java). In order to bring the best experience to the user (mostly because at that time RN animations were on the main thread), @xinthink decided to write this lib using native code. This is why you have to "npm link", because you need to tell React Native that you'll use native code. 

This works great for React Native apps, but not with "Create-React-Native-App" because they don't allow you to use native code. cf https://github.com/react-community/create-react-native-app#what-are-the-limitations-of-create-react-native-app
