### ISSUE TITLE
MKCardStyles returns Object with numbers? 

### ISSUE THREAD

**Issue by Gattermeier** [xinthink/react-native-material-kit#63]
Peculiar. MKCardStyles returns an object with properties containing numbers rather than style objects? 

Object {card: 106, image: 107, title: 108, content: 109, action: 110…}

I am logging like this: 

```
var MK = require('react-native-material-kit');

var {
  MKCardStyles
} = MK;

console.log('MKCardStyles', MKCardStyles)
```

Thoughts? Ideas?

**Comment by Crash--** [comment]
I think it's the default behavior of React Native. If you take a look at the React Dev Tool when debugging an app, you'll see, at the first place, number instead of style object. 

What are you trying to do with logging MKCardStyles? If you want to see the Style object, you can find it here: https://github.com/xinthink/react-native-material-kit/blob/master/lib/mdl/cards/styles.js

**Comment by Gattermeier** [comment]
I see, I was just confused. And the styles in large parts don't work with Android (yet) that's why I thought there might be a weird bug.

**Comment by Crash--** [comment]
Oh well, I didn't try with Android. Are you fixing the issues? If not I can take a look in a few days.

**Comment by xinthink** [comment]
hi @Gattermeier,
Like @Crash-- said, that's how RN StyleSheet works, we can only retrieve the style IDs from the StyleSheetRegistry so far, not the style object.

Can you specify the problem on Android? And would you mind post the code here, or a demo on rnplay.org to reproduce the problem?

It seems working fine on my Genymotion emulator.

**Comment by alexprice91** [comment]
Inactive. Closing.
